# install-service-startup.ps1
$startupDir = [System.IO.Path]::Combine($env:APPDATA, 'Microsoft\Windows\Start Menu\Programs\Startup')
$targetVbs = Join-Path $startupDir "StreamDockBridgeService.vbs"
$legacyCmd = Join-Path $startupDir "StreamDockBridgeService.cmd"
$serviceDistPath = Join-Path $PSScriptRoot "packages\service\dist\index.js"
$nodePath = (Get-Command node).Source

if (-not (Test-Path $serviceDistPath)) {
    Write-Error "Service dist file not found at $serviceDistPath. Run 'yarn build' first."
    exit 1
}

# The service's own data directory, alongside secret.key and iconCache.json. A logon
# launch that dies leaves no evidence when its output goes to a console nobody sees,
# which is exactly what made the last failure undiagnosable. Truncated per logon, so
# this stays a "what happened this session" file rather than an unbounded log.
$dataDir = Join-Path $env:APPDATA 'StreamDockBridge'
if (-not (Test-Path $dataDir)) {
    New-Item -ItemType Directory -Path $dataDir -Force | Out-Null
}
$logPath = Join-Path $dataDir 'service.log'

# A .vbs wrapper rather than a .cmd, because Explorer runs Startup items with a normal
# window style: a .cmd puts a console window on the owner's desktop for the life of the
# service, and closing that window takes the service with it. WScript.Shell.Run with
# window style 0 starts it with no window at all. cmd.exe is still the thing that
# understands redirection, so it stays in the middle - hidden, and only long enough to
# wire stdout/stderr to the log.
$vbsContent = @"
' StreamDockBridge logon launcher. Generated by install-service-startup.ps1 - do not edit.
' Starts the existing localhost service hidden at logon. Remove it with
' uninstall-service-startup.ps1, or just delete this file.
Set shell = CreateObject("WScript.Shell")
shell.Run "cmd /c """"$nodePath"" ""$serviceDistPath"" > ""$logPath"" 2>&1""", 0, False
"@

# Written without a BOM. Set-Content -Encoding utf8 on Windows PowerShell 5.1 emits one,
# and a BOM ahead of the first line is a parse error for the interpreter that reads it.
$noBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($targetVbs, $vbsContent, $noBom)
Write-Host "Installed Windows logon startup launcher with absolute paths to: $targetVbs"

# Exactly one startup registration. An install that left the old .cmd in place would
# hand the owner two logon launches racing for port 17337.
if (Test-Path $legacyCmd) {
    Remove-Item -Path $legacyCmd -Force
    Write-Host "Removed superseded startup entry: $legacyCmd"
}

# Same reason, for the process rather than the registration: this script is run on a
# live desktop, and the service may already be up from a previous logon or install.
$running = Get-CimInstance Win32_Process -Filter "Name='node.exe'" |
    Where-Object { $_.CommandLine -like "*packages\service\dist\index.js*" }
foreach ($proc in $running) {
    Stop-Process -Id $proc.ProcessId -Force -ErrorAction SilentlyContinue
    Write-Host "Stopped already-running service process (PID: $($proc.ProcessId))."
}
if ($running) {
    Start-Sleep -Seconds 1
}

# Launched through the installed launcher rather than by re-deriving the command here,
# so what this script proves working is the same artifact logon will run.
Start-Process -FilePath "wscript.exe" -ArgumentList "`"$targetVbs`"" -WindowStyle Hidden
Write-Host "StreamDockBridge background service launched from installed startup launcher."
Write-Host "Service log: $logPath"
